version: '3.8'

services:
  languagetool:
    image: erikvl87/languagetool:latest
    container_name: languagetool-server
    ports:
      - "8081:8010"
    environment:
      - Java_Xms=512m
      - Java_Xmx=2g
      - langtool_languageModel=/ngrams
      - langtool_fasttextModel=/fasttext/lid.176.bin
    volumes:
      # Optional: Add n-gram data for better suggestions
      # - ./ngrams:/ngrams:ro
      # Optional: Add custom dictionaries
      - ./custom-dictionaries:/custom-dictionaries:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/v2/languages"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alternative: Use the official Java image with LanguageTool
  # languagetool-java:
  #   image: openjdk:11-jre-slim
  #   container_name: languagetool-java
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./LanguageTool-6.3:/languagetool
  #   command: >
  #     java -cp /languagetool/languagetool-server.jar
  #     org.languagetool.server.HTTPServer
  #     --port 8081 --public --allow-origin "*"
  #   restart: unless-stopped