global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ebook-pipeline'

scrape_configs:
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'ebook-server'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          instance: 'ebook-redis'

  # Application metrics
  - job_name: 'ebook-app'
    static_configs:
      - targets: ['host.docker.internal:9464'] # App metrics endpoint
        labels:
          app: 'ebook-pipeline'

  # BullMQ metrics (if exposed)
  - job_name: 'bullmq'
    static_configs:
      - targets: ['host.docker.internal:9465']
        labels:
          app: 'ebook-queues'